//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.8806
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cabinet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1200px_Breezeicons_actions_22_im_user_svg {
            get {
                object obj = ResourceManager.GetObject("1200px-Breezeicons-actions-22-im-user.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _208_2081718_past_history_icon_png_blue {
            get {
                object obj = ResourceManager.GetObject("208-2081718_past-history-icon-png-blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _296 {
            get {
                object obj = ResourceManager.GetObject("296", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _36111_66874_ApplePasswordManagerResources_01_xl_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("36111-66874-ApplePasswordManagerResources-01-xl-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _36111_66874_ApplePasswordManagerResources_01_xl_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("36111-66874-ApplePasswordManagerResources-01-xl-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _378px_Lock_grey_alt_3_svg {
            get {
                object obj = ResourceManager.GetObject("378px-Lock-grey-alt-3.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _53590 {
            get {
                object obj = ResourceManager.GetObject("53590", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _60740 {
            get {
                object obj = ResourceManager.GetObject("60740", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _65ba488626025cff82f091336fbf94bb {
            get {
                object obj = ResourceManager.GetObject("65ba488626025cff82f091336fbf94bb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6904410_preview {
            get {
                object obj = ResourceManager.GetObject("6904410_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _768px_Circle_icons_profile_svg {
            get {
                object obj = ResourceManager.GetObject("768px-Circle-icons-profile.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _8_512 {
            get {
                object obj = ResourceManager.GetObject("8-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _8_5121 {
            get {
                object obj = ResourceManager.GetObject("8-5121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_1_ico {
            get {
                object obj = ResourceManager.GetObject("add-1.ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap anatomo {
            get {
                object obj = ResourceManager.GetObject("anatomo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap anatomo1 {
            get {
                object obj = ResourceManager.GetObject("anatomo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap antecedents {
            get {
                object obj = ResourceManager.GetObject("antecedents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Antu_emblem_locked_svg {
            get {
                object obj = ResourceManager.GetObject("Antu_emblem-locked.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Awicons_Vista_Artistic_Add {
            get {
                object obj = ResourceManager.GetObject("Awicons-Vista-Artistic-Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B_Verma {
            get {
                object obj = ResourceManager.GetObject("B Verma", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bio {
            get {
                object obj = ResourceManager.GetObject("bio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Businessman_52px {
            get {
                object obj = ResourceManager.GetObject("Businessman_52px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap debut {
            get {
                object obj = ResourceManager.GetObject("debut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap endo {
            get {
                object obj = ResourceManager.GetObject("endo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap endos {
            get {
                object obj = ResourceManager.GetObject("endos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap endoscopie {
            get {
                object obj = ResourceManager.GetObject("endoscopie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap evo {
            get {
                object obj = ResourceManager.GetObject("evo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ex_rad {
            get {
                object obj = ResourceManager.GetObject("ex rad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ex_radio {
            get {
                object obj = ResourceManager.GetObject("ex radio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap examen {
            get {
                object obj = ResourceManager.GetObject("examen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Forgot_Password_48px {
            get {
                object obj = ResourceManager.GetObject("Forgot Password_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormatFactorydrops_of_water_3_wallpaper_1024x768 {
            get {
                object obj = ResourceManager.GetObject("FormatFactorydrops_of_water_3-wallpaper-1024x768", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrailOfficialDegus_size_restricted {
            get {
                object obj = ResourceManager.GetObject("FrailOfficialDegus-size_restricted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrailOfficialDegus_size_restricted1 {
            get {
                object obj = ResourceManager.GetObject("FrailOfficialDegus-size_restricted1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gastroscopy_logo_icon_design_vector_15613150_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("gastroscopy-logo-icon-design-vector-15613150-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_pasien_png_1 {
            get {
                object obj = ResourceManager.GetObject("icon-pasien-png-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kisscc0_laboratory_flasks_beaker_chemistry_chemical_substa_test_tube_5_5b71f238520832_073818401534194232336 {
            get {
                object obj = ResourceManager.GetObject("kisscc0-laboratory-flasks-beaker-chemistry-chemical-substa-test-tube-5-5b71f23852" +
                        "0832.073818401534194232336", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kisspng_computer_icons_login_scalable_vector_graphics_emai_5be7376911c6b4_4735764415418796570728_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-login-scalable-vector-graphics-emai-5be7376911c6b4.4735764" +
                        "415418796570728-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kisspng_habitat_for_humanity_organization_brand_central_pa_5afa97134a5d92_5727961515263721153046_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("kisspng-habitat-for-humanity-organization-brand-central-pa-5afa97134a5d92.5727961" +
                        "515263721153046-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kisspng_habitat_for_humanity_organization_brand_central_pa_5afa97134a5d921 {
            get {
                object obj = ResourceManager.GetObject("kisspng-habitat-for-humanity-organization-brand-central-pa-5afa97134a5d921", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kyo_Tux_Delikate_Add {
            get {
                object obj = ResourceManager.GetObject("Kyo-Tux-Delikate-Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loader {
            get {
                object obj = ResourceManager.GetObject("loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Loader02 {
            get {
                object obj = ResourceManager.GetObject("Loader02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loader1 {
            get {
                object obj = ResourceManager.GetObject("loader1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loading_small {
            get {
                object obj = ResourceManager.GetObject("loading_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loading_small1 {
            get {
                object obj = ResourceManager.GetObject("loading_small1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_512pxGREY {
            get {
                object obj = ResourceManager.GetObject("lock_512pxGREY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_icon {
            get {
                object obj = ResourceManager.GetObject("lock-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap maladies {
            get {
                object obj = ResourceManager.GetObject("maladies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap maladies1 {
            get {
                object obj = ResourceManager.GetObject("maladies1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap medicament {
            get {
                object obj = ResourceManager.GetObject("medicament", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap output_onlinepngtools {
            get {
                object obj = ResourceManager.GetObject("output-onlinepngtools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap output_onlinepngtools1 {
            get {
                object obj = ResourceManager.GetObject("output-onlinepngtools1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap patients_dans_salle_attente_medecins_hopital_53562_2402 {
            get {
                object obj = ResourceManager.GetObject("patients-dans-salle-attente-medecins-hopital_53562-2402", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap photo {
            get {
                object obj = ResourceManager.GetObject("photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap photo_1557683316_973673baf926 {
            get {
                object obj = ResourceManager.GetObject("photo-1557683316-973673baf926", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pílula_teste {
            get {
                object obj = ResourceManager.GetObject("Pílula teste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap power_154692_960_720 {
            get {
                object obj = ResourceManager.GetObject("power-154692_960_720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap precription_png_trans {
            get {
                object obj = ResourceManager.GetObject("precription png trans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pres {
            get {
                object obj = ResourceManager.GetObject("pres", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prescript {
            get {
                object obj = ResourceManager.GetObject("prescript", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap print {
            get {
                object obj = ResourceManager.GetObject("print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Profile_gray {
            get {
                object obj = ResourceManager.GetObject("Profile_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rad {
            get {
                object obj = ResourceManager.GetObject("rad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap radio {
            get {
                object obj = ResourceManager.GetObject("radio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap radio1 {
            get {
                object obj = ResourceManager.GetObject("radio1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap radio2 {
            get {
                object obj = ResourceManager.GetObject("radio2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap radioo {
            get {
                object obj = ResourceManager.GetObject("radioo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Speech_bubble_svg {
            get {
                object obj = ResourceManager.GetObject("Speech_bubble.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stethoscope_outil_pour_cardiologue_medecin_equipement_outil_medical_concept_diagnostic_medecine_284704_62 {
            get {
                object obj = ResourceManager.GetObject("stethoscope-outil-pour-cardiologue-medecin-equipement-outil-medical-concept-diagn" +
                        "ostic-medecine_284704-62", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stomach_endoscopy_endoscope_in_stomach_through_vector_33432367 {
            get {
                object obj = ResourceManager.GetObject("stomach-endoscopy-endoscope-in-stomach-through-vector-33432367", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap téléchargement_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("téléchargement-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_password {
            get {
                object obj = ResourceManager.GetObject("textbox_password", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_1 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_10 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_11 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_12 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_13 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_14 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_15 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_16 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_17 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_18 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_19 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_2 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_20 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_21 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_22 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_23 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_24 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_3 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_4 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_5 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_6 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_7 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_8 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_9 {
            get {
                object obj = ResourceManager.GetObject("textbox_user_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox_user_Clicked {
            get {
                object obj = ResourceManager.GetObject("textbox_user_Clicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unnamed {
            get {
                object obj = ResourceManager.GetObject("unnamed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_512 {
            get {
                object obj = ResourceManager.GetObject("user-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wait {
            get {
                object obj = ResourceManager.GetObject("wait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Webp_net_resizeimage {
            get {
                object obj = ResourceManager.GetObject("Webp.net-resizeimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
